export const COUPON_ADD_REQUEST = 'COUPON_ADD_REQUEST'
export const COUPON_ADD_SUCCESS = 'COUPON_ADD_SUCCESS'
export const COUPON_ADD_FAIL = 'COUPON_ADD_FAIL'
export const COUPON_ADD_RESET = 'COUPON_ADD_RESET'

export const COUPON_LIST_REQUEST = 'COUPON_LIST_REQUEST'
export const COUPON_LIST_SUCCESS = 'COUPON_LIST_SUCCESS'
export const COUPON_LIST_FAIL = 'COUPON_LIST_FAIL'

export const COUPON_DELETE_REQUEST = 'COUPON_DELETE_REQUEST'
export const COUPON_DELETE_SUCCESS = 'COUPON_DELETE_SUCCESS'
export const COUPON_DELETE_FAIL = 'COUPON_DELETE_FAIL'
