export const DASHBOARD_DETAILS_REQUEST = 'DASHBOARD_DETAILS_REQUEST'
export const DASHBOARD_DETAILS_SUCCESS = 'DASHBOARD_DETAILS_SUCCESS'
export const DASHBOARD_DETAILS_FAIL = 'DASHBOARD_DETAILS_FAIL'
